name: Test

on:
  - pull_request
  - push

jobs:
  test-extension:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cd extension; yarn; yarn test
  test-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cd site; yarn; yarn test
